baseURL = "http://xndr.name/"
title = "/home/xndr_78"
languageCode = "en-us"
googleAnalytics = "UA-9638300-1"
sectionPagesMenu = "main"
theme = "xndr-name-theme"
[menu]
    [[menu.main]]
        name = "/home/xndr_78"
        url = "/"
        weight = 1
