name: deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@v1
      - name: Build and deploy
        uses: benmatselby/hugo-deploy-gh-pages@main
          env:
            HUGO_VERSION: 0.127.0
            TARGET_REPO: xndr78/xndr.github.io
            TARGET_BRANCH: master
            TOKEN: ${{ secrets.TOKEN }}
            HUGO_ARGS: '--minify --cleanDestinationDir'
            CNAME: xndr.name